// SIH Scenario 4: Dense Market Area
import type { ScenarioConfig } from '@/types/simulation';

export const denseMarketScenario: ScenarioConfig = {
  id: 'sih-004-dense-market',
  name: 'Dense Market Area',
  description: 'Navigate through a congested market street with heavy pedestrian and vehicle traffic, pushcarts, and a very narrow drivable corridor.',
  roadType: 'market_road',
  trafficDensity: 'extreme',
  weather: 'clear',
  visibility: 'moderate',
  difficulty: 'extreme',
  egoStart: { x: 50, y: 300 },
  egoEnd: { x: 950, y: 300 },
  waypoints: [
    { x: 150, y: 300 }, { x: 250, y: 298 }, { x: 350, y: 302 },
    { x: 450, y: 299 }, { x: 550, y: 301 }, { x: 650, y: 300 },
    { x: 750, y: 299 }, { x: 850, y: 301 }, { x: 940, y: 300 },
  ],
  roadBoundaries: [
    [{ x: 0, y: 278 }, { x: 1000, y: 278 }],
    [{ x: 0, y: 322 }, { x: 1000, y: 322 }],
  ],
  agents: [
    // Multiple pedestrians
    ...Array.from({ length: 8 }, (_, i) => ({
      id: `market-ped-${i}`,
      type: 'pedestrian' as const,
      position: { x: 120 + i * 100, y: 285 + (i % 3) * 10 },
      velocity: { x: (i % 2 === 0 ? 1 : -1) * 1.2, y: (i % 3 - 1) * 0.5 },
      speed: 1.3,
      heading: i % 2 === 0 ? 0 : Math.PI,
      width: 0.5, length: 0.5,
      isActive: true,
      behavior: { type: 'straight' as const, speed: 1.2 },
      trail: [],
    })),
    // Autos
    {
      id: 'market-auto-1',
      type: 'auto_rickshaw' as const,
      position: { x: 200, y: 300 },
      velocity: { x: 2, y: 0 },
      speed: 2,
      heading: 0,
      width: 1.5, length: 3.0,
      isActive: true,
      behavior: { type: 'straight', speed: 2 },
      trail: [],
    },
    {
      id: 'market-auto-2',
      type: 'auto_rickshaw' as const,
      position: { x: 550, y: 302 },
      velocity: { x: -1.5, y: 0 },
      speed: 1.5,
      heading: Math.PI,
      width: 1.5, length: 3.0,
      isActive: true,
      behavior: { type: 'straight', speed: 1.5 },
      trail: [],
    },
    // Bicycle
    {
      id: 'market-bicycle',
      type: 'bicycle' as const,
      position: { x: 380, y: 295 },
      velocity: { x: 3, y: 0 },
      speed: 3,
      heading: 0,
      width: 0.6, length: 1.8,
      isActive: true,
      behavior: { type: 'straight', speed: 3 },
      trail: [],
    },
    // Pushcart blocking
    {
      id: 'pushcart-block',
      type: 'pushcart' as const,
      position: { x: 450, y: 300 },
      velocity: { x: 0.2, y: 0 },
      speed: 0.2,
      heading: 0,
      width: 1.8, length: 2.5,
      isActive: false,
      behavior: { type: 'stationary', speed: 0 },
      trail: [],
    },
  ],
  obstacles: [
    { id: 'stall-1', position: { x: 180, y: 282 }, width: 3, height: 2, type: 'static', label: 'Market Stall' },
    { id: 'stall-2', position: { x: 320, y: 318 }, width: 3, height: 2, type: 'static', label: 'Market Stall' },
    { id: 'stall-3', position: { x: 480, y: 282 }, width: 4, height: 2, type: 'static', label: 'Market Stall' },
    { id: 'stall-4', position: { x: 650, y: 319 }, width: 3, height: 2, type: 'static', label: 'Market Stall' },
    { id: 'stall-5', position: { x: 800, y: 282 }, width: 3, height: 2, type: 'static', label: 'Market Stall' },
  ],
  events: [
    {
      id: 'evt-pushcart',
      triggerTime: 8,
      eventType: 'pushcart_block',
      agentId: 'pushcart-block',
      description: 'Pushcart vendor blocking narrow market lane',
    },
    {
      id: 'evt-ped-surge',
      triggerTime: 13,
      eventType: 'pedestrian_cross',
      description: 'Group of pedestrians crossing market road',
    },
  ],
  duration: 100,
  tags: ['SIH', 'market', 'dense', 'pedestrians', 'pushcart', 'low-speed'],
};
