// SIH Scenario 2: Busy Urban Intersection (No Traffic Signal)
import type { ScenarioConfig } from '@/types/simulation';

export const urbanIntersectionScenario: ScenarioConfig = {
  id: 'sih-002-urban-intersection',
  name: 'Busy Urban Intersection',
  description: 'Navigate a chaotic unsignalized urban intersection with cars, auto-rickshaws, motorcycles, and pedestrians merging informally.',
  roadType: 'urban_intersection',
  trafficDensity: 'high',
  weather: 'clear',
  visibility: 'good',
  difficulty: 'extreme',
  egoStart: { x: 50, y: 300 },
  egoEnd: { x: 950, y: 300 },
  waypoints: [
    { x: 200, y: 300 },
    { x: 400, y: 300 },
    { x: 500, y: 300 },
    { x: 700, y: 300 },
    { x: 900, y: 300 },
  ],
  roadBoundaries: [
    [{ x: 0, y: 265 }, { x: 1000, y: 265 }],
    [{ x: 0, y: 335 }, { x: 1000, y: 335 }],
    // Cross street
    [{ x: 465, y: 0 }, { x: 465, y: 1000 }],
    [{ x: 535, y: 0 }, { x: 535, y: 1000 }],
  ],
  agents: [
    // Crossing traffic from right
    {
      id: 'car-cross-1',
      type: 'car',
      position: { x: 500, y: 150 },
      velocity: { x: 0, y: 6 },
      speed: 6,
      heading: Math.PI / 2,
      width: 2.0,
      length: 4.5,
      isActive: true,
      behavior: { type: 'straight', speed: 6 },
      trail: [],
    },
    // Auto merging from left
    {
      id: 'auto-merge',
      type: 'auto_rickshaw',
      position: { x: 380, y: 310 },
      velocity: { x: 4, y: -1 },
      speed: 4.1,
      heading: -0.24,
      width: 1.5,
      length: 3.0,
      isActive: true,
      behavior: { type: 'turning', speed: 4.1 },
      trail: [],
    },
    // Motorcycle cutting in
    {
      id: 'moto-cut',
      type: 'motorcycle',
      position: { x: 450, y: 290 },
      velocity: { x: 8, y: 2 },
      speed: 8.2,
      heading: 0.24,
      width: 0.9,
      length: 2.0,
      isActive: false,
      behavior: { type: 'straight', speed: 8.2 },
      trail: [],
    },
    // Pedestrians crossing
    {
      id: 'ped-cross-1',
      type: 'pedestrian',
      position: { x: 495, y: 260 },
      velocity: { x: 0, y: 1.2 },
      speed: 1.2,
      heading: Math.PI / 2,
      width: 0.5,
      length: 0.5,
      isActive: false,
      behavior: { type: 'crossing', speed: 1.2 },
      trail: [],
    },
    {
      id: 'ped-cross-2',
      type: 'pedestrian',
      position: { x: 510, y: 258 },
      velocity: { x: 0, y: 1.4 },
      speed: 1.4,
      heading: Math.PI / 2,
      width: 0.5,
      length: 0.5,
      isActive: false,
      behavior: { type: 'crossing', speed: 1.4 },
      trail: [],
    },
    // Bus from opposite direction
    {
      id: 'bus-oncoming',
      type: 'bus',
      position: { x: 750, y: 298 },
      velocity: { x: -8, y: 0 },
      speed: 8,
      heading: Math.PI,
      width: 2.5,
      length: 9.0,
      isActive: true,
      behavior: { type: 'straight', speed: 8 },
      trail: [],
    },
  ],
  obstacles: [
    { id: 'divider-1', position: { x: 500, y: 245 }, width: 60, height: 3, type: 'static', label: 'Median' },
  ],
  events: [
    {
      id: 'evt-moto-cut',
      triggerTime: 38,
      eventType: 'vehicle_cut_in',
      agentId: 'moto-cut',
      description: 'Motorcycle cutting in at intersection',
    },
    {
      id: 'evt-ped-cross',
      triggerTime: 42,
      eventType: 'pedestrian_cross',
      agentId: 'ped-cross-1',
      description: 'Pedestrians crossing unsignalized intersection',
    },
    {
      id: 'evt-ped-cross-2',
      triggerTime: 43,
      eventType: 'pedestrian_cross',
      agentId: 'ped-cross-2',
      description: 'Second pedestrian crossing',
    },
  ],
  duration: 75,
  tags: ['SIH', 'urban', 'intersection', 'no-signal', 'mixed-traffic'],
};
