// SIH Scenario 1: Unmarked Village Road
// Tests: Adaptive path generation, obstacle avoidance, mixed traffic, animals

import type { ScenarioConfig, Agent, Obstacle } from '@/types/simulation';

export const villageRoadScenario: ScenarioConfig = {
  id: 'sih-001-village-road',
  name: 'Unmarked Village Road',
  description: 'Navigate a narrow, unmarked rural road with mixed traffic including motorcycles, cyclists, pedestrians, and cattle.',
  roadType: 'village_road',
  trafficDensity: 'medium',
  weather: 'clear',
  visibility: 'good',
  difficulty: 'hard',
  egoStart: { x: 50, y: 300 },
  egoEnd: { x: 950, y: 300 },
  waypoints: [
    { x: 150, y: 300 },
    { x: 300, y: 295 },
    { x: 450, y: 305 },
    { x: 600, y: 298 },
    { x: 750, y: 302 },
    { x: 900, y: 300 },
  ],
  roadBoundaries: [
    // Top boundary
    [{ x: 0, y: 270 }, { x: 1000, y: 272 }],
    // Bottom boundary  
    [{ x: 0, y: 332 }, { x: 1000, y: 330 }],
  ],
  agents: [
    {
      id: 'motorcycle-1',
      type: 'motorcycle',
      position: { x: 200, y: 298 },
      velocity: { x: 5, y: 0 },
      speed: 5,
      heading: 0,
      width: 0.9,
      length: 2.0,
      isActive: true,
      behavior: { type: 'straight', speed: 5 },
      trail: [],
    },
    {
      id: 'bicycle-1',
      type: 'bicycle',
      position: { x: 350, y: 308 },
      velocity: { x: 3, y: 0 },
      speed: 3,
      heading: 0,
      width: 0.6,
      length: 1.8,
      isActive: true,
      behavior: { type: 'straight', speed: 3 },
      trail: [],
    },
    {
      id: 'oncoming-car',
      type: 'car',
      position: { x: 600, y: 295 },
      velocity: { x: -7, y: 0 },
      speed: 7,
      heading: Math.PI,
      width: 2.0,
      length: 4.5,
      isActive: true,
      behavior: { type: 'straight', speed: 7 },
      trail: [],
    },
    {
      id: 'cattle-1',
      type: 'animal',
      position: { x: 480, y: 280 },
      velocity: { x: 0.5, y: 1.2 },
      speed: 1.3,
      heading: Math.PI / 3,
      width: 1.5,
      length: 2.5,
      isActive: false, // activated by event trigger
      behavior: { type: 'crossing', speed: 1.3 },
      trail: [],
    },
    {
      id: 'pedestrian-1',
      type: 'pedestrian',
      position: { x: 320, y: 270 },
      velocity: { x: 0, y: 1.5 },
      speed: 1.5,
      heading: Math.PI / 2,
      width: 0.5,
      length: 0.5,
      isActive: false,
      behavior: { type: 'crossing', speed: 1.5 },
      trail: [],
    },
    {
      id: 'auto-1',
      type: 'auto_rickshaw',
      position: { x: 750, y: 302 },
      velocity: { x: -4, y: 0 },
      speed: 4,
      heading: Math.PI,
      width: 1.5,
      length: 3.0,
      isActive: true,
      behavior: { type: 'straight', speed: 4 },
      trail: [],
    },
  ],
  obstacles: [
    { id: 'obs-1', position: { x: 420, y: 297 }, width: 1.5, height: 1.5, type: 'static', label: 'Pothole' },
    { id: 'obs-2', position: { x: 680, y: 310 }, width: 2, height: 2, type: 'static', label: 'Rock' },
  ],
  events: [
    {
      id: 'evt-cattle',
      triggerTime: 6,
      eventType: 'animal_enter',
      agentId: 'cattle-1',
      description: 'Cattle entering road from field',
    },
    {
      id: 'evt-ped',
      triggerTime: 10,
      eventType: 'pedestrian_cross',
      agentId: 'pedestrian-1',
      description: 'Pedestrian crossing unmarked road',
    },
  ],
  duration: 90,
  tags: ['SIH', 'village', 'unmarked', 'cattle', 'mixed-traffic'],
};
